### ISSUE TITLE
Squares on objective or constraints

### ISSUE THREAD

**Issue by JuanStat95** [dirkschumacher/rmpk#34]
Can I use squares with this package? Like the distance formula for example.
Thanks in advance

**Comment by dirkschumacher** [comment]
I think so. Can you give me an example?

**Comment by JuanStat95** [comment]
I'm trying a close enough TSP, 
![image](https://user-images.githubusercontent.com/59689964/72154231-60d42d00-33b0-11ea-9ada-47553e22835f.png)

**Comment by dirkschumacher** [comment]
Year, that should be possible except the `square` function. But I think you do not need it.
