### ISSUE TITLE
Minimizing the sum of square error

### ISSUE THREAD

**Issue by mcanigueral** [dirkschumacher/rmpk#41]
Hi,
as a continuation of issue #38 , I apply the following objective function in order to obtain an optimal variable (`Vopt`) the most similar as possible to `PV` vector (like Sum of square error, SSE):

<a href="https://www.codecogs.com/eqnedit.php?latex=\text{min}&space;\sum_{i&space;=&space;1}^{n}&space;(Vopt_{i}&space;-&space;PV_{i})^{2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\text{min}&space;\sum_{i&space;=&space;1}^{n}&space;(Vopt_{i}&space;-&space;PV_{i})^{2}" title="\text{min} \sum_{i = 1}^{n} (Vopt_{i} - PV_{i})^{2}" /></a>

I use `quadprog` solver with the following code:
```r
v <- c(20, 15, 10, 15, 10, 20)
pv <- c(0, 10, 40, 40, 10, 0)
n <- length(v)
V <- sum(v)
model <- MIPModel(solver = ROI_solver("quadprog"))
opt_v <- model$add_variable(i = 1:n, type = "continuous", lb = 0)
model$set_objective(sum_expr((opt_v[i] - pv[i])^2, i = 1:n), "min")
model$add_constraint(sum_expr(opt_v[i], i = 1:n) == V)
model$optimize()
ov <- model$get_variable_value(opt_v [i]) %>% pull(value)
```
And I obtain:
![image](https://user-images.githubusercontent.com/34347594/77532182-a58e4100-6e94-11ea-806a-e2a5b2533976.png)

However, this is not the optimal solution since the curve that fits better the objective goal is that one (`my_ov`):
![image](https://user-images.githubusercontent.com/34347594/77532994-4fba9880-6e96-11ea-8592-1e68d33bffdc.png)

```r
my_ov <- c(0, 10, 40, 40, 0, 0)
sum((ov - pv)^2)
# 3025
sum((my_ov - pv)^2)
# 100
```
Is this a problem of the solver? I have tested the same with `alabama` and `qpoases` and I get the same. To be honest, I have never done it with other languages like Matlab or Python, so I don't have a reference. I'm just testing and learning now.

Thanks!

**Comment by dirkschumacher** [comment]
Thanks a lot. Will investigate!

**Comment by dirkschumacher** [comment]
The variables from `get_variable_value` have an undefined sorting. This will give you the correct ordering and a better solution than `my_ov`.
```R
ov <- model$get_variable_value(opt_v [i])
ov <- ov[order(ov$i), "value"]
```

**Comment by mcanigueral** [comment]
Oh! Perfect, sorry for that!

**Comment by dirkschumacher** [comment]
Thanks for testing out the package!
